CREATE TABLE COUNTERS (
       ID             BIGSERIAL PRIMARY KEY,
       CODE_KKS       VARCHAR(50) NOT NULL,
       PULSE_COUNT    REAL NOT NULL DEFAULT 0,
       CONC_1SEC      REAL NOT NULL DEFAULT 0,
       CONC_10SEC     REAL NOT NULL DEFAULT 0,
       CONC_100SEC    REAL NOT NULL DEFAULT 0,
       REG_TIME       TIMESTAMPTZ NOT NULL DEFAULT NOW()
       );
