CREATE TABLE COUNTERS (
       ID             BIGSERIAL PRIMARY KEY,
       CODE_KKS       VARCHAR(50) NOT NULL,
       PULSE_COUNT    NUMERIC(10,2) NOT NULL DEFAULT 0,
       CONC_1SEC      NUMERIC(10,2) NOT NULL DEFAULT 0,
       CONC_10SEC     NUMERIC(10,2) NOT NULL DEFAULT 0,
       CONC_100SEC    NUMERIC(10,2) NOT NULL DEFAULT 0,
       REG_TIME       TIMESTAMPTZ NOT NULL DEFAULT NOW()
       );
