CREATE TABLE COUNTERS (
       ID             BIGSERIAL PRIMARY KEY,
       CODE_KKS       VARCHAR(50) NOT NULL,
       SIGNAL_CURRENT NUMERIC(10,2) NOT NULL DEFAULT 0,
       TEMPERATURE    NUMERIC(10,2) NOT NULL DEFAULT 0,
       REG_TIME       TIMESTAMPTZ NOT NULL DEFAULT NOW()
       );
